# things.py (Updated)

items_materials = {
"material_activity_christmas2024": "?",
    "material_activity_coin_bug_feature": "?",
    "material_activity_coin_school": "?",
    "material_ancient_weapon_fragment": "?",
    "material_battery": "?",
    "material_c17_book_1":0,
    "material_c17_book_2":0,
    "material_c18_book_1":0,
    "material_c18_book_2":0,
    "material_c20_book_1":0,
    "material_c20_book_2":0,
    "material_c21_book_1":0,
    "material_c21_book_2":0,
    "material_cell": "?",
    "material_dead_cell":0,
    "material_fertilize": "?",
    "material_fish": "?",
    "material_fragment_c6h8o6": "?",
    "material_fragment_zulan": "?",
    "material_gear": "?",
    "material_grain": "?",
    "material_iron": "?",
    "material_jewelry_fragment": "?",
    "material_magic_black": "?",
    "material_magic_blue": "?",
    "material_magic_cyan": "?",
    "material_magic_green": "?",
    "material_magic_orange": "?",
    "material_magic_purple": "?",
    "material_magic_red": "?",
    "material_ticket": "?",
    "material_ticket_bossrush": "?",
    "material_wood": "?",
    "material_skill_Druid_1":0,
    "material_skill_Officer_2":0,
    "material_skill_Paladin_2":0,
    "material_skill_Priest_1":0,
    "material_skill_Viking_2":0,
    "material_skill_Warlock_1":0,
    "material_skin_fragment_boss01":0,
    "material_skin_fragment_boss02":0,
    "material_skin_fragment_boss07":0,
    "material_skin_fragment_boss08":0,
    "material_skin_fragment_boss10":0,
    "material_skin_fragment_boss15":0,
    "material_skin_fragment_boss16":0,
    "material_skin_fragment_boss18":0,
    "material_skin_fragment_boss19":0,
    "material_skin_fragment_boss23":0,
    "material_skin_fragment_boss30":0,
    "material_skin_fragment_c12_s06":0,
    "material_skin_fragment_c12_s12":0,
    "material_skin_fragment_c12_s6":0,
    "material_skin_fragment_c14_s6":0,
    "material_skin_fragment_c16_s6":0,
    "material_skin_fragment_c5_s8":0,
    "material_skin_fragment_c7_s12":0,
    "material_skin_fragment_flag":0,
    "material_skin_fragment_law":0,
    "material_skin_fragment_shop":0,
    "material_tape_alien":1,
    "material_tape_aurora":1,
    "material_tape_aurora_wrong_version":1,
    "material_tape_bgm_multi_room_skin_17":1,
    "material_tape_boss1":1,
    "material_tape_boss2":1,
    "material_tape_boss3":1,
    "material_tape_castle":1,
    "material_tape_civilization":1,
    "material_tape_dark":1,
    "material_tape_defence":1,
    "material_tape_doctor_6":1,
    "material_tape_dragon_boy":1,
    "material_tape_easter":1,
    "material_tape_elves_17":1,
    "material_tape_end_temple":1,
    "material_tape_forest":1,
    "material_tape_grave":1,
    "material_tape_graveyard":1,
    "material_tape_hall":1,
    "material_tape_hall_cny":1,
    "material_tape_halloween":1,
    "material_tape_ice":1,
    "material_tape_icecave":1,
    "material_tape_irontide_multiroom":1,
    "material_tape_island":1,
    "material_tape_level_2g":1,
    "material_tape_level_4g":1,
    "material_tape_monster":1,
    "material_tape_mythology":1,
    "material_tape_necromancer_16":1,
    "material_tape_neon":1,
    "material_tape_opera":1,
    "material_tape_party":1,
    "material_tape_rock_girl":1,
    "material_tape_ruins":1,
    "material_tape_stars":1,
    "material_tape_stronghold_wave":1,
    "material_tape_summer":1,
    "material_tape_swamp":1,
    "material_tape_sword_master_4":1,
    "material_tape_thunderstorm":1,
    "material_tape_volcano":1,
    "material_tape_zhuazhua":1
}

items_plants = {
    "plant_banboo_seed": "?",
    "plant_binary_tree_seed": "?",
    "plant_cactus_seed": "?",
    "plant_carrot_seed": "?",
    "plant_clivia_seed": "?",
    "plant_datura_seed": "?",
    "plant_defend_flower_seed": "?",
    "plant_dragon_tree_seed": "?",
    "plant_eator_seed": "?",
    "plant_fantastic_flower_seed": "?",
    "plant_gear_flower_seed": "?",
    "plant_gem_flower_seed": "?",
    "plant_gem_tree_seed": "?",
    "plant_heptacolor_seed": "?",
    "plant_iron_tree_seed": "?",
    "plant_lavender_seed": "?",
    "plant_lotus_seed": "?",
    "plant_lycoris_seed": "?",
    "plant_magic_flower_seed": "?",
    "plant_mandrake_seed": "?",
    "plant_mirror_plane_flower_seed": "?",
    "plant_mushroom_gold_seed": "?",
    "plant_mushroom_seed": "?",
    "plant_pumpkin_seed": "?",
    "plant_qilixiang_seed": "?",
    "plant_radar_seed": "?",
    "plant_rainbow_grass_seed": "?",
    "plant_roselle_seed": "?",
    "plant_rosemary_seed": "?",
    "plant_shallot_seed": "?",
    "plant_silver_poplar_seed": "?",
    "plant_strange_flower_seed": "?",
    "plant_tree_seed": "?",
    "plant_trumpet_seed": "?",
    "plant_vine_seed": "?",
    "plant_watermelon_seed": "?",
    "plant_worm_seed": "?",
    "plant_xmas_seed": "?"
}

blueprints = {
    "blueprint_m_mech_2": "Researched",
    "blueprint_m_mech_3": "Researched",
    "blueprint_m_mech_4": "Researched",
    "blueprint_m_mech_5": "Researched",
    "blueprint_m_mech_6": "Researched",
    "blueprint_m_mech_7": "Researched",
    "blueprint_m_mech_8": "Researched",
    "blueprint_m_mecha_normal_2s": "Researched",
    "blueprint_m_mecha_normal_b": "Researched",
    "blueprint_m_mecha_normal_d": "Researched",
    "blueprint_m_mecha_normal_e": "Researched",
    "blueprint_multi_room_skin_1": "Researched",
    "blueprint_multi_room_skin_2": "Researched",
    "blueprint_room_decorate_drink_seller": "Researched",
    "blueprint_room_decorate_egg_machine": "Researched",
    "blueprint_room_decorate_fishbowl": "Researched",
    "blueprint_room_decorate_lobby": "Researched",
    "blueprint_room_decorate_magic_well": "Researched",
    "blueprint_room_decorate_mysteriou_statue": "Researched",
    "blueprint_room_decorate_pet_food": "Researched",
    "blueprint_room_decorate_plant": "Researched",
    "blueprint_room_decorate_safe": "Researched",
    "blueprint_room_decorate_trash_can": "Researched",
    "blueprint_skill_Alchemist_0": "Researched",
    "blueprint_skill_Alchemist_1": "Researched",
    "blueprint_skill_Alchemist_2": "Researched",
    "blueprint_skill_Assassin_0": "Researched",
    "blueprint_skill_Assassin_1": "Researched",
    "blueprint_skill_Assassin_2": "Researched",
    "blueprint_skill_Druid_0": "Researched",
    "blueprint_skill_Druid_1": "Researched",
    "blueprint_skill_Druid_2": "Researched",
    "blueprint_skill_Elves_0": "Researched",
    "blueprint_skill_Elves_1": "Researched",
    "blueprint_skill_Elves_2": "Researched",
    "blueprint_skill_Engineer_0": "Researched",
    "blueprint_skill_Engineer_1": "Researched",
    "blueprint_skill_Engineer_2": "Researched",
    "blueprint_skill_Envoy_0": "Researched",
    "blueprint_skill_Knight_0": "Researched",
    "blueprint_skill_Knight_1": "Researched",
    "blueprint_skill_Knight_2": "Researched",
    "blueprint_skill_Mage_0": "Researched",
    "blueprint_skill_Mage_1": "Researched",
    "blueprint_skill_Mage_2": "Researched",
    "blueprint_skill_Necromancer_0": "Researched",
    "blueprint_skill_Necromancer_1": "Researched",
    "blueprint_skill_Necromancer_2": "Researched",
    "blueprint_skill_Officer_0": "Researched",
    "blueprint_skill_Officer_1": "Researched",
    "blueprint_skill_Officer_2": "Researched",
    "blueprint_skill_Paladin_0": "Researched",
    "blueprint_skill_Paladin_1": "Researched",
    "blueprint_skill_Paladin_2": "Researched",
    "blueprint_skill_Priest_0": "Researched",
    "blueprint_skill_Priest_1": "Researched",
    "blueprint_skill_Priest_2": "Researched",
    "blueprint_skill_Ranger_0": "Researched",
    "blueprint_skill_Ranger_1": "Researched",
    "blueprint_skill_Ranger_2": "Researched",
    "blueprint_skill_Robot_0": "Researched",
    "blueprint_skill_Robot_1": "Researched",
    "blueprint_skill_Robot_2": "Researched",
    "blueprint_skill_Taoist_0": "Researched",
    "blueprint_skill_Taoist_1": "Researched",
    "blueprint_skill_Taoist_2": "Researched",
    "blueprint_skill_Transcendent_0": "Researched",
    "blueprint_skill_Vampire_0": "Researched",
    "blueprint_skill_Vampire_1": "Researched",
    "blueprint_skill_Vampire_2": "Researched",
    "blueprint_skill_Viking_0": "Researched",
    "blueprint_skill_Viking_1": "Researched",
    "blueprint_skill_Viking_2": "Researched",
    "blueprint_skill_Warlock_1": "Researched",
    "blueprint_skill_Werewolf_0": "Researched",
    "blueprint_skill_Werewolf_1": "Researched",
    "blueprint_skill_Werewolf_2": "Researched",
    "blueprint_skin_alchemist_0": "Researched",
    "blueprint_skin_alchemist_1": "Researched",
    "blueprint_skin_alchemist_14": "Researched",
    "blueprint_skin_alchemist_2": "Researched",
    "blueprint_skin_alchemist_3": "Researched",
    "blueprint_skin_alchemist_4": "Researched",
    "blueprint_skin_alchemist_5": "Researched",
    "blueprint_skin_alchemist_6": "Researched",
    "blueprint_skin_alchemist_7": "Researched",
    "blueprint_skin_alchemist_8": "Researched",
    "blueprint_skin_alchemist_9": "Researched",
    "blueprint_skin_assassin_0": "Researched",
    "blueprint_skin_assassin_1": "Researched",
    "blueprint_skin_assassin_10": "Researched",
    "blueprint_skin_assassin_11": "Researched",
    "blueprint_skin_assassin_12": "Researched",
    "blueprint_skin_assassin_2": "Researched",
    "blueprint_skin_assassin_3": "Researched",
    "blueprint_skin_assassin_4": "Researched",
    "blueprint_skin_assassin_5": "Researched",
    "blueprint_skin_assassin_6": "Researched",
    "blueprint_skin_assassin_7": "Researched",
    "blueprint_skin_assassin_8": "Researched",
    "blueprint_skin_assassin_9": "Researched",
    "blueprint_skin_druid_0": "Researched",
    "blueprint_skin_druid_1": "Researched",
    "blueprint_skin_druid_2": "Researched",
    "blueprint_skin_druid_3": "Researched",
    "blueprint_skin_druid_4": "Researched",
    "blueprint_skin_druid_5": "Researched",
    "blueprint_skin_druid_6": "Researched",
    "blueprint_skin_druid_7": "Researched",
    "blueprint_skin_druid_8": "Researched",
    "blueprint_skin_druid_9": "Researched",
    "blueprint_skin_elves_0": "Researched",
    "blueprint_skin_elves_1": "Researched",
    "blueprint_skin_elves_10": "Researched",
    "blueprint_skin_elves_2": "Researched",
    "blueprint_skin_elves_3": "Researched",
    "blueprint_skin_elves_4": "Researched",
    "blueprint_skin_elves_5": "Researched",
    "blueprint_skin_elves_6": "Researched",
    "blueprint_skin_elves_7": "Researched",
    "blueprint_skin_elves_8": "Researched",
    "blueprint_skin_elves_9": "Researched",
    "blueprint_skin_engineer_0": "Researched",
    "blueprint_skin_engineer_1": "Researched",
    "blueprint_skin_engineer_10": "Researched",
    "blueprint_skin_engineer_11": "Researched",
    "blueprint_skin_engineer_12": "Researched",
    "blueprint_skin_engineer_2": "Researched",
    "blueprint_skin_engineer_3": "Researched",
    "blueprint_skin_engineer_4": "Researched",
    "blueprint_skin_engineer_5": "Researched",
    "blueprint_skin_engineer_6": "Researched",
    "blueprint_skin_engineer_7": "Researched",
    "blueprint_skin_engineer_8": "Researched",
    "blueprint_skin_engineer_9": "Researched",
    "blueprint_skin_envoy_0": "Researched",
    "blueprint_skin_knight_0": "Researched",
    "blueprint_skin_knight_1": "Researched",
    "blueprint_skin_knight_10": "Researched",
    "blueprint_skin_knight_11": "Researched",
    "blueprint_skin_knight_12": "Researched",
    "blueprint_skin_knight_13": "Researched",
    "blueprint_skin_knight_2": "Researched",
    "blueprint_skin_knight_20": "Researched",
    "blueprint_skin_knight_3": "Researched",
    "blueprint_skin_knight_4": "Researched",
    "blueprint_skin_knight_5": "Researched",
    "blueprint_skin_knight_6": "Researched",
    "blueprint_skin_knight_7": "Researched",
    "blueprint_skin_knight_8": "Researched",
    "blueprint_skin_knight_9": "Researched",
    "blueprint_skin_mage_0": "Researched",
    "blueprint_skin_mage_1": "Researched",
    "blueprint_skin_mage_10": "Researched",
    "blueprint_skin_mage_11": "Researched",
    "blueprint_skin_mage_12": "Researched",
    "blueprint_skin_mage_2": "Researched",
    "blueprint_skin_mage_3": "Researched",
    "blueprint_skin_mage_4": "Researched",
    "blueprint_skin_mage_5": "Researched",
    "blueprint_skin_mage_6": "Researched",
    "blueprint_skin_mage_7": "Researched",
    "blueprint_skin_mage_8": "Researched",
    "blueprint_skin_mage_9": "Researched",
    "blueprint_skin_necromancer_0": "Researched",
    "blueprint_skin_necromancer_1": "Researched",
    "blueprint_skin_necromancer_2": "Researched",
    "blueprint_skin_necromancer_3": "Researched",
    "blueprint_skin_necromancer_4": "Researched",
    "blueprint_skin_necromancer_5": "Researched",
    "blueprint_skin_necromancer_6": "Researched",
    "blueprint_skin_officer_0": "Researched",
    "blueprint_skin_officer_1": "Researched",
    "blueprint_skin_officer_2": "Researched",
    "blueprint_skin_officer_3": "Researched",
    "blueprint_skin_officer_4": "Researched",
    "blueprint_skin_officer_5": "Researched",
    "blueprint_skin_officer_6": "Researched",
    "blueprint_skin_paladin_0": "Researched",
    "blueprint_skin_paladin_1": "Researched",
    "blueprint_skin_paladin_10": "Researched",
    "blueprint_skin_paladin_11": "Researched",
    "blueprint_skin_paladin_12": "Researched",
    "blueprint_skin_paladin_2": "Researched",
    "blueprint_skin_paladin_3": "Researched",
    "blueprint_skin_paladin_4": "Researched",
    "blueprint_skin_paladin_5": "Researched",
    "blueprint_skin_paladin_6": "Researched",
    "blueprint_skin_paladin_7": "Researched",
    "blueprint_skin_paladin_8": "Researched",
    "blueprint_skin_paladin_9": "Researched",
    "blueprint_skin_priest_0": "Researched",
    "blueprint_skin_priest_1": "Researched",
    "blueprint_skin_priest_10": "Researched",
    "blueprint_skin_priest_11": "Researched",
    "blueprint_skin_priest_2": "Researched",
    "blueprint_skin_priest_3": "Researched",
    "blueprint_skin_priest_4": "Researched",
    "blueprint_skin_priest_5": "Researched",
    "blueprint_skin_priest_6": "Researched",
    "blueprint_skin_priest_7": "Researched",
    "blueprint_skin_priest_8": "Researched",
    "blueprint_skin_priest_9": "Researched",
    "blueprint_skin_ranger_0": "Researched",
    "blueprint_skin_ranger_1": "Researched",
    "blueprint_skin_ranger_10": "Researched",
    "blueprint_skin_ranger_11": "Researched",
    "blueprint_skin_ranger_12": "Researched",
    "blueprint_skin_ranger_13": "Researched",
    "blueprint_skin_ranger_2": "Researched",
    "blueprint_skin_ranger_3": "Researched",
    "blueprint_skin_ranger_4": "Researched",
    "blueprint_skin_ranger_5": "Researched",
    "blueprint_skin_ranger_6": "Researched",
    "blueprint_skin_ranger_7": "Researched",
    "blueprint_skin_ranger_8": "Researched",
    "blueprint_skin_ranger_9": "Researched",
    "blueprint_skin_robot_0": "Researched",
    "blueprint_skin_robot_1": "Researched",
    "blueprint_skin_robot_10": "Researched",
    "blueprint_skin_robot_11": "Researched",
    "blueprint_skin_robot_12": "Researched",
    "blueprint_skin_robot_2": "Researched",
    "blueprint_skin_robot_3": "Researched",
    "blueprint_skin_robot_4": "Researched",
    "blueprint_skin_robot_5": "Researched",
    "blueprint_skin_robot_6": "Researched",
    "blueprint_skin_robot_7": "Researched",
    "blueprint_skin_robot_8": "Researched",
    "blueprint_skin_robot_9": "Researched",
    "blueprint_skin_taoist_0": "Researched",
    "blueprint_skin_taoist_1": "Researched",
    "blueprint_skin_taoist_2": "Researched",
    "blueprint_skin_taoist_3": "Researched",
    "blueprint_skin_taoist_4": "Researched",
    "blueprint_skin_taoist_5": "Researched",
    "blueprint_skin_taoist_6": "Researched",
    "blueprint_skin_taoist_7": "Researched",
    "blueprint_skin_transcendent_0": "Researched",
    "blueprint_skin_vampire_0": "Researched",
    "blueprint_skin_vampire_1": "Researched",
    "blueprint_skin_vampire_10": "Researched",
    "blueprint_skin_vampire_2": "Researched",
    "blueprint_skin_vampire_3": "Researched",
    "blueprint_skin_vampire_4": "Researched",
    "blueprint_skin_vampire_5": "Researched",
    "blueprint_skin_vampire_6": "Researched",
    "blueprint_skin_vampire_7": "Researched",
    "blueprint_skin_vampire_8": "Researched",
    "blueprint_skin_vampire_9": "Researched",
    "blueprint_skin_viking_0": "Researched",
    "blueprint_skin_viking_1": "Researched",
    "blueprint_skin_viking_10": "Researched",
    "blueprint_skin_viking_11": "Researched",
    "blueprint_skin_viking_12": "Researched",
    "blueprint_skin_viking_19": "Researched",
    "blueprint_skin_viking_2": "Researched",
    "blueprint_skin_viking_3": "Researched",
    "blueprint_skin_viking_4": "Researched",
    "blueprint_skin_viking_5": "Researched",
    "blueprint_skin_viking_6": "Researched",
    "blueprint_skin_viking_7": "Researched",
    "blueprint_skin_viking_8": "Researched",
    "blueprint_skin_viking_9": "Researched",
    "blueprint_skin_werewolf_0": "Researched",
    "blueprint_skin_werewolf_1": "Researched",
    "blueprint_skin_werewolf_10": "Researched",
    "blueprint_skin_werewolf_11": "Researched",
    "blueprint_skin_werewolf_12": "Researched",
    "blueprint_skin_werewolf_13": "Researched",
    "blueprint_skin_werewolf_14": "Researched",
    "blueprint_skin_werewolf_2": "Researched",
    "blueprint_skin_werewolf_3": "Researched",
    "blueprint_skin_werewolf_4": "Researched",
    "blueprint_skin_werewolf_5": "Researched",
    "blueprint_skin_werewolf_6": "Researched",
    "blueprint_skin_werewolf_7": "Researched",
    "blueprint_skin_werewolf_8": "Researched",
    "blueprint_skin_werewolf_9": "Researched",
    "blueprint_transform_weapon_beheaded": "Researched",
    "blueprint_transform_weapon_envoy": "Researched",
    "blueprint_transform_weapon_ninja": "Researched",
    "blueprint_transform_weapon_specialforces": "Researched",
    "blueprint_transform_weapon_transcendent": "Researched",
    "blueprint_weapon_184": "Researched",
    "blueprint_weapon_188": "Researched",
    "blueprint_weapon_189": "Researched",
    "blueprint_weapon_195": "Researched",
    "blueprint_weapon_211": "Researched",
    "blueprint_weapon_212": "Researched",
    "blueprint_weapon_213": "Researched",
    "blueprint_weapon_217": "Researched",
    "blueprint_weapon_223": "Researched",
    "blueprint_weapon_224": "Researched",
    "blueprint_weapon_237": "Researched",
    "blueprint_weapon_238": "Researched",
    "blueprint_weapon_240": "Researched",
    "blueprint_weapon_242": "Researched",
    "blueprint_weapon_252": "Researched",
    "blueprint_weapon_294": "Researched",
    "blueprint_weapon_321": "Researched",
    "blueprint_weapon_333": "Researched",
    "blueprint_weapon_340": "Researched",
    "blueprint_weapon_341": "Researched",
    "blueprint_weapon_342": "Researched",
    "blueprint_weapon_344": "Researched",
    "blueprint_weapon_356": "Researched",
    "blueprint_weapon_370": "Researched",
    "blueprint_weapon_380": "Researched",
    "blueprint_weapon_381": "Researched",
    "blueprint_weapon_383": "Researched",
    "blueprint_weapon_385": "Researched",
    "blueprint_weapon_386": "Researched",
    "blueprint_weapon_387": "Researched",
    "blueprint_weapon_392": "Researched",
    "blueprint_weapon_393": "Researched",
    "blueprint_weapon_394": "Researched",
    "blueprint_weapon_395": "Researched",
    "blueprint_weapon_396": "Researched",
    "blueprint_weapon_397": "Researched",
    "blueprint_weapon_398": "Researched",
    "blueprint_weapon_bossrushfinal": "Researched",
    "blueprint_weapon_bossrushfinalA": "Researched",
    "blueprint_weapon_bossrushfinalB": "Researched",
    "blueprint_weapon_cg_0": "Researched",
    "blueprint_weapon_cg_1": "Researched",
    "blueprint_weapon_cg_2": "Researched",
    "blueprint_weapon_cg_3": "Researched",
    "blueprint_weapon_fel_fabric": "Researched",
    "blueprint_weapon_fish_rod_a": "Researched",
    "blueprint_weapon_fish_rod_b": "Researched",
    "blueprint_weapon_fish_rod_c": "Researched",
    "blueprint_weapon_fish_rod_d": "Researched",
    "garden_skin_1": "Got",
    "garden_skin_2": "Got",
    "garden_skin_3": "Got",
    "garden_skin_4": "Got",
    "hall_skin_1": "Got",
    "hall_skin_2": "Got",
    "hall_skin_3": "Got",
    "hall_skin_4": "Got",
    "hall_skin_5": "Got",
    "magic_area_skin_1": "Got",
    "magic_area_skin_2": "Got",
    "magic_area_skin_3": "Got",
    "magic_area_skin_4": "Got",
    "mboar2": "Researched",
    "mcristal": "Researched",
    "mspider": "Researched",
    "multi_room_skin_10": "Got",
    "multi_room_skin_11": "Got",
    "multi_room_skin_12": "Got",
    "multi_room_skin_13": "Got",
    "multi_room_skin_14": "Got",
    "multi_room_skin_15": "Got",
    "multi_room_skin_16": "Got",
    "multi_room_skin_17": "Got",
    "multi_room_skin_18": "Got",
    "multi_room_skin_19": "Got",
    "multi_room_skin_3": "Got",
    "multi_room_skin_4": "Got",
    "multi_room_skin_5": "Got",
    "multi_room_skin_6": "Got",
    "multi_room_skin_7": "Got",
    "multi_room_skin_8": "Got",
    "multi_room_skin_9": "Got",
    "mvaken": "Researched",
    "work_shop_skin_1": "Got",
    "work_shop_skin_2": "Got",
    "work_shop_skin_3": "Got",
    "work_shop_skin_4": "Got"
  }


skills = [
    'c_Airbender_skill_0_unlock',
    'c_Airbender_skill_1_unlock',
    'c_Airbender_skill_2_unlock',
    'c_Alchemist_skill_0_unlock',
    'c_Alchemist_skill_1_unlock',
    'c_Alchemist_skill_2_unlock',
    'c_ArcaneKnight_skill_0_unlock',
    'c_Assassin_skill_0_unlock',
    'c_Assassin_skill_1_unlock',
    'c_Assassin_skill_2_unlock',
    'c_Beheaded_skill_0_unlock',
    'c_CostumePrince_skill_1_unlock',
    'c_Doctor_skill_0_unlock',
    'c_Doctor_skill_1_unlock',
    'c_Druid_skill_0_unlock',
    'c_Druid_skill_1_unlock',
    'c_Druid_skill_2_unlock',
    'c_Elves_skill_0_unlock',
    'c_Elves_skill_1_unlock',
    'c_Elves_skill_2_unlock',
    'c_Engineer_skill_0_unlock',
    'c_Engineer_skill_1_unlock',
    'c_Engineer_skill_2_unlock',
    'c_Envoy_skill_0_unlock',
    'c_Knight_skill_0_unlock',
    'c_Knight_skill_1_unlock',
    'c_Knight_skill_2_unlock',
    'c_Lancer_skill_0_unlock',
    'c_Mage_skill_0_unlock',
    'c_Mage_skill_1_unlock',
    'c_Mage_skill_2_unlock',
    'c_Miner_skill_0_unlock',
    'c_Miner_skill_1_unlock',
    'c_Miner_skill_2_unlock',
    'c_Necromancer_skill_0_unlock',
    'c_Necromancer_skill_1_unlock',
    'c_Necromancer_skill_2_unlock',
    'c_Ninja_skill_0_unlock',
    'c_Officer_skill_0_unlock',
    'c_Officer_skill_1_unlock',
    'c_Officer_skill_2_unlock',
    'c_Paladin_skill_0_unlock',
    'c_Paladin_skill_1_unlock',
    'c_Paladin_skill_2_unlock',
    'c_Priest_skill_0_unlock',
    'c_Priest_skill_1_unlock',
    'c_Priest_skill_2_unlock',
    'c_Ranger_skill_0_unlock',
    'c_Ranger_skill_1_unlock',
    'c_Ranger_skill_2_unlock',
    'c_Robot_skill_0_unlock',
    'c_Robot_skill_1_unlock',
    'c_Robot_skill_2_unlock',
    'c_SpecialForces_skill_0_unlock',
    'c_SwordMaster_skill_0_unlock',
    'c_Taoist_skill_0_unlock',
    'c_Taoist_skill_1_unlock',
    'c_Taoist_skill_2_unlock',
    'c_Transcendent_skill_0_unlock',
    'c_TrapMaster_skill_0_unlock',
    "c_TrapMaster_skill_1_unlock",
    "c_TrapMaster_skill_2_unlock",
    'c_Vampire_skill_0_unlock',
    'c_Vampire_skill_1_unlock',
    'c_Vampire_skill_2_unlock',
    'c_Viking_skill_0_unlock',
    'c_Viking_skill_1_unlock',
    'c_Viking_skill_2_unlock',
    'c_Warliege_skill_0_unlock',
    'c_Warlock_skill_0_unlock',
    'c_Warlock_skill_1_unlock',
    'c_Warlock_skill_2_unlock',
    'c_Werewolf_skill_0_unlock',
    'c_Werewolf_skill_1_unlock',
    'c_Werewolf_skill_2_unlock'
]

chip_list = [
    "Regen", "Rhythm", "Thorns", "Fatal", "Surge", "Gritty", "ProofOfHero",
    "Burst", "ProofOfTyrant", "Flexible", "Shock", "Zealot", "Barrier",
    "Abundant", "Light", "Vigorous", "Concerto", "Raven"
]

evolvable_weapons = [
    "weapon_006", "weapon_010", "weapon_007", "weapon_038", "weapon_111",
    "weapon_127", "weapon_231", "weapon_275", "weapon_233", "weapon_239",
    "weapon_311", "weapon_315", "weapon_316", "weapon_345", "weapon_008"
]

follower_list = [
    "HuangFuSong", "ShuiJing", "MaYunLu", "LvQiLing", "WenYuan", "TaishiCi"
]

mount_list = [
    "HuiYing", "MengHuo", "NanManXiang", "ZhuaHuangFeiDian"
]