
items_materials = {
    "material_ancient_weapon_fragment": "?",
    "material_battery": "?",
    "material_cell": "?",
    "material_fertilize": "?",
    "material_fish": "?",
    "material_fragment_c6h8o6": "?",
    "material_fragment_zulan": "?",
    "material_gear": "?",
    "material_grain": "?",
    "material_iron": "?",
    "material_jewelry_fragment": 99,
    "material_magic_black": "?",
    "material_magic_blue": "?",
    "material_magic_cyan": "?",
    "material_magic_green": "?",
    "material_magic_orange": "?",
    "material_magic_purple": "?",
    "material_magic_red": "?",
    "material_soul_fragment": "?",
    "material_ticket": "?",
    "material_ticket_bossrush": "?",
    "material_wood": "?",
    "material_tape_alien": 1,
    "material_tape_aurora": 1,
    "material_tape_aurora_wrong_version": 1,
    "material_tape_boss1": 1,
    "material_tape_boss2": 1,
    "material_tape_boss3": 1,
    "material_tape_boss4": 1,
    "material_tape_castle": 1,
    "material_tape_civilization": 1,
    "material_tape_dark": 1,
    "material_tape_defence": 1,
    "material_tape_easter": 1,
    "material_tape_end_temple": 1,
    "material_tape_forest": 1,
    "material_tape_grave": 1,
    "material_tape_graveyard": 1,
    "material_tape_hall": 1,
    "material_tape_hall_cny": 1,
    "material_tape_halloween": 1,
    "material_tape_ice": 1,
    "material_tape_icecave": 1,
    "material_tape_irontide_multiroom": 1,
    "material_tape_island": 1,
    "material_tape_level_2g": 1,
    "material_tape_level_4g": 1,
    "material_tape_monster": 1,
    "material_tape_mythology": 1,
    "material_tape_neon": 1,
    "material_tape_opera": 1,
    "material_tape_party": 1,
    "material_tape_ruins": 1,
    "material_tape_stars": 2,
    "material_tape_stronghold_wave": 1,
    "material_tape_swamp": 1,
    "material_tape_thunderstorm": 1,
    "material_tape_volcano": 1,
    "material_tape_zhuazhua": 1
}

items_plants = {
    "plant_banboo_seed": "?",
    "plant_binary_tree_seed": "?",
    "plant_cactus_seed": "?",
    "plant_carrot_seed": "?",
    "plant_clivia_seed": "?",
    "plant_datura_seed": "?",
    "plant_defend_flower_seed": "?",
    "plant_dragon_tree_seed": "?",
    "plant_eator_seed": "?",
    "plant_fantastic_flower_seed": "?",
    "plant_firecracker_seed": "?",
    "plant_gear_flower_seed": "?",
    "plant_gem_flower_seed": "?",
    "plant_gem_tree_seed": "?",
    "plant_heptacolor_seed": "?",
    "plant_iron_tree_seed": "?",
    "plant_lavender_seed": "?",
    "plant_lotus_seed": "?",
    "plant_lycoris_seed": "?",
    "plant_magic_flower_seed": "?",
    "plant_mandrake_seed": "?",
    "plant_mirror_plane_flower_seed": "?",
    "plant_mushroom_gold_seed": "?",
    "plant_mushroom_seed": "?",
    "plant_pumpkin_seed": "?",
    "plant_qilixiang_seed": "?",
    "plant_radar_seed": "?",
    "plant_rainbow_grass_seed": "?",
    "plant_roselle_seed": "?",
    "plant_rosemary_seed": "?",
    "plant_shallot_seed": "?",
    "plant_silver_poplar_seed": "?",
    "plant_strange_flower_seed": "?",
    "plant_tree_seed": "?",
    "plant_trumpet_seed": "?",
    "plant_vine_seed": "?",
    "plant_watermelon_seed": "?",
    "plant_worm_seed": "?",
    "plant_xmas_seed": "?"
}

blueprints = {
    "Blueprint_weapon_370":"Got",
    "blueprint_m_mech_2":"Researched",
    "blueprint_m_mech_3":"Researched",
    "blueprint_m_mech_4":"Researched",
    "blueprint_m_mech_5":"Researched",
    "blueprint_m_mech_6":"Researched",
    "blueprint_m_mech_7":"Researched",
    "blueprint_m_mecha_normal_2s":"Researched",
    "blueprint_m_mecha_normal_b":"Researched",
    "blueprint_m_mecha_normal_d":"Researched",
    "blueprint_m_mecha_normal_e":"Researched",
    "blueprint_room_decorate_drink_seller":"Researched",
    "blueprint_room_decorate_fishbowl":"Researched",
    "blueprint_room_decorate_magic_well":"Researched",
    "blueprint_room_decorate_mysteriou_statue":"Researched",
    "blueprint_skill_Druid_1":"Researched",
    "blueprint_skill_Officer_2":"Researched",
    "blueprint_skill_Paladin_2":"Researched",
    "blueprint_skill_Priest_1":"Researched",
    "blueprint_skill_Viking_2":"Researched",
    "blueprint_skill_Warlock_1":"Researched",
    "blueprint_skin_alchemist_14":"Researched",
    "blueprint_skin_alchemist_8":"Researched",
    "blueprint_skin_elves_6":"Researched",
    "blueprint_skin_elves_9":"Researched",
    "blueprint_skin_engineer_8":"Researched",
    "blueprint_skin_knight_20":"Researched",
    "blueprint_skin_mage_7":"Researched",
    "blueprint_skin_necromancer_1":"Researched",
    "blueprint_skin_necromancer_13":"Researched",
    "blueprint_skin_necromancer_6":"Researched",
    "blueprint_skin_officer_5":"Researched",
    "blueprint_skin_paladin_12":"Researched",
    "blueprint_skin_paladin_7":"Researched",
    "blueprint_skin_priest_5":"Researched",
    "blueprint_skin_ranger_12":"Researched",
    "blueprint_skin_ranger_6":"Researched",
    "blueprint_skin_robot_12":"Researched",
    "blueprint_skin_robot_6":"Researched",
    "blueprint_skin_taoist_5":"Researched",
    "blueprint_skin_taoist_6":"Researched",
    "blueprint_skin_vampire_7":"Researched",
    "blueprint_skin_viking_19":"Researched",
    "blueprint_skin_viking_4":"Researched",
    "blueprint_skin_viking_6":"Researched",
    "blueprint_skin_werewolf_9":"Researched",
    "blueprint_transform_weapon_beheaded":"Researched",
    "blueprint_transform_weapon_envoy":"Researched",
    "blueprint_transform_weapon_ninja":"Researched",
    "blueprint_transform_weapon_specialforces":"Researched",
    "blueprint_transform_weapon_transcendent":"Researched",
    "blueprint_weapon_184":"Researched",
    "blueprint_weapon_188":"Researched",
    "blueprint_weapon_189":"Researched",
    "blueprint_weapon_195":"Researched",
    "blueprint_weapon_211":"Researched",
    "blueprint_weapon_212":"Researched",
    "blueprint_weapon_213":"Researched",
    "blueprint_weapon_217":"Researched",
    "blueprint_weapon_223":"Researched",
    "blueprint_weapon_224":"Researched",
    "blueprint_weapon_237":"Researched",
    "blueprint_weapon_238":"Researched",
    "blueprint_weapon_240":"Researched",
    "blueprint_weapon_242":"Researched",
    "blueprint_weapon_252":"Researched",
    "blueprint_weapon_294":"Researched",
    "blueprint_weapon_321":"Researched",
    "blueprint_weapon_333":"Researched",
    "blueprint_weapon_340":"Researched",
    "blueprint_weapon_341":"Researched",
    "blueprint_weapon_342":"Researched",
    "blueprint_weapon_344":"Researched",
    "blueprint_weapon_356":"Researched",
    "blueprint_weapon_370":"Researched",
    "blueprint_weapon_380":"Researched",
    "blueprint_weapon_381":"Researched",
    "blueprint_weapon_bossrushfinal":"Researched",
    "blueprint_weapon_bossrushfinalA":"Researched",
    "blueprint_weapon_bossrushfinalB":"Researched",
    "blueprint_weapon_cg_0":"Researched",
    "blueprint_weapon_cg_1":"Researched",
    "blueprint_weapon_cg_2":"Researched",
    "blueprint_weapon_cg_3":"Researched",
    "blueprint_weapon_fish_rod_a":"Researched",
    "blueprint_weapon_fish_rod_b":"Researched",
    "blueprint_weapon_fish_rod_c":"Researched",
    "blueprint_weapon_fish_rod_d":"Researched",
    "garden_skin_1":"Got",
    "garden_skin_2":"Got",
    "hall_skin_1":"Got",
    "hall_skin_2":"Got",
    "hall_skin_3":"Got",
    "hall_skin_4":"Got",
    "magic_area_skin_1":"Got",
    "magic_area_skin_2":"Got",
    "mboar2":"Researched",
    "mcristal":"Researched",
    "mspider":"Researched",
    "multi_room_skin_1":"Got",
    "multi_room_skin_10":"Got",
    "multi_room_skin_11":"Got",
    "multi_room_skin_12":"Got",
    "multi_room_skin_13":"Got",
    "multi_room_skin_14":"Got",
    "multi_room_skin_15":"Got",
    "multi_room_skin_16":"Got",
    "multi_room_skin_2":"Got",
    "multi_room_skin_3":"Got",
    "multi_room_skin_4":"Got",
    "multi_room_skin_5":"Got",
    "multi_room_skin_6":"Got",
    "multi_room_skin_7":"Got",
    "multi_room_skin_8":"Got",
    "multi_room_skin_9":"Got",
    "mvaken":"Researched",
    "work_shop_skin_1":"Got",
    "work_shop_skin_2":"Got",
    "work_shop_skin_3":"Got"
  }


skills = [
    'c_Airbender_skill_0_unlock',
    'c_Airbender_skill_1_unlock',
    'c_Airbender_skill_2_unlock',
    'c_Alchemist_skill_0_unlock',
    'c_Alchemist_skill_1_unlock',
    'c_Alchemist_skill_2_unlock',
    'c_ArcaneKnight_skill_0_unlock',
    'c_Assassin_skill_0_unlock',
    'c_Assassin_skill_1_unlock',
    'c_Assassin_skill_2_unlock',
    'c_Beheaded_skill_0_unlock',
    'c_CostumePrince_skill_1_unlock',
    'c_Doctor_skill_0_unlock',
    'c_Doctor_skill_1_unlock',
    'c_Druid_skill_0_unlock',
    'c_Druid_skill_1_unlock',
    'c_Druid_skill_2_unlock',
    'c_Elves_skill_0_unlock',
    'c_Elves_skill_1_unlock',
    'c_Elves_skill_2_unlock',
    'c_Engineer_skill_0_unlock',
    'c_Engineer_skill_1_unlock',
    'c_Engineer_skill_2_unlock',
    'c_Envoy_skill_0_unlock',
    'c_Knight_skill_0_unlock',
    'c_Knight_skill_1_unlock',
    'c_Knight_skill_2_unlock',
    'c_Lancer_skill_0_unlock',
    'c_Mage_skill_0_unlock',
    'c_Mage_skill_1_unlock',
    'c_Mage_skill_2_unlock',
    'c_Miner_skill_0_unlock',
    'c_Miner_skill_1_unlock',
    'c_Miner_skill_2_unlock',
    'c_Necromancer_skill_0_unlock',
    'c_Necromancer_skill_1_unlock',
    'c_Necromancer_skill_2_unlock',
    'c_Ninja_skill_0_unlock',
    'c_Officer_skill_0_unlock',
    'c_Officer_skill_1_unlock',
    'c_Officer_skill_2_unlock',
    'c_Paladin_skill_0_unlock',
    'c_Paladin_skill_1_unlock',
    'c_Paladin_skill_2_unlock',
    'c_Priest_skill_0_unlock',
    'c_Priest_skill_1_unlock',
    'c_Priest_skill_2_unlock',
    'c_Ranger_skill_0_unlock',
    'c_Ranger_skill_1_unlock',
    'c_Ranger_skill_2_unlock',
    'c_Robot_skill_0_unlock',
    'c_Robot_skill_1_unlock',
    'c_Robot_skill_2_unlock',
    'c_SpecialForces_skill_0_unlock',
    'c_SwordMaster_skill_0_unlock',
    'c_Taoist_skill_0_unlock',
    'c_Taoist_skill_1_unlock',
    'c_Taoist_skill_2_unlock',
    'c_Transcendent_skill_0_unlock',
    'c_TrapMaster_skill_0_unlock',
    'c_TrapMaster_skill_1_unlock',
    'c_TrapMaster_skill_2_unlock',
    'c_Vampire_skill_0_unlock',
    'c_Vampire_skill_1_unlock',
    'c_Vampire_skill_2_unlock',
    'c_Viking_skill_0_unlock',
    'c_Viking_skill_1_unlock',
    'c_Viking_skill_2_unlock',
    'c_Warliege_skill_0_unlock',
    'c_Warlock_skill_0_unlock',
    'c_Warlock_skill_1_unlock',
    'c_Warlock_skill_2_unlock',
    'c_Werewolf_skill_0_unlock',
    'c_Werewolf_skill_1_unlock',
    'c_Werewolf_skill_2_unlock'
]
